sudo: false
language: node_js
addons:
  firefox: "43.0b3"
env:
  global:
  - DISPLAY=:99.0
  - JPM_FIREFOX_BINARY=/usr/local/bin/firefox
before_install:
- openssl aes-256-cbc -K $encrypted_a56afc9f0968_key -iv $encrypted_a56afc9f0968_iv
  -in .transifexrc.enc -out .transifexrc -d
- sh -e /etc/init.d/xvfb start
before_script:
- npm install -g grunt-cli
after_success:
- ./node_modules/.bin/codecov
branches:
  except:
  - gh-pages
notifications:
  email:
    on_failure: change
before_deploy:
- grunt build
deploy:
  provider: releases
  api_key:
    secure: FhQ1eXOReVAgWbhWU3XC/zzbbarHk8G5x3X8EBU1HIdS6nbOfMphIj3fPh78wCSF19EouuOpVr4sl4Sk1KBV7NoeHAwWKmxTeNxnxy2K2cQ/SIraOm5Emls5ckXINZx51IVW/mcKtXJANLXu9Wo4q+7ZJ6ZPpVmNK1qEBSx8ITc=
  file: "jid0-z2wAjbeFD5dTCgsj70eQ6UAqQl4@jetpack-${TRAVIS_TAG}.xpi"
  on:
    repo: freaktechnik/justintv-stream-notifications
    tags: true
